### ISSUE TITLE
Production link is still not available

### ISSUE THREAD

**Issue by wsw70** [jgallen23/toc#68]
Reopening https://github.com/jgallen23/toc/issues/66:

```
https://raw.githubusercontent.com/jgallen23/toc/master/dist/toc.min.js
```

leads to a 404. Maybe it would be worthwhile to publish the production code on a CDN?

**Comment by jgallen23** [comment]
https://raw.githubusercontent.com/jgallen23/toc/0.3.2/dist/toc.min.js

**Comment by tholu** [comment]
Still broken here: http://projects.jga.me/toc/
